### ISSUE TITLE
Add a black list for pools (old pools)

### ISSUE THREAD

**Issue by alejandrordzl** [stakeordie/EthereumBridgeFrontend#13]
Inside `userStores.ts` add a list of black (disabled) pools.

```ts 
public blacklistedPools = string[] ;
```
Inside UserStore constructure define all black listed pools

```ts
//Define black listed pools
    this.blacklistedPools=["<pool_address>","<pool_address>"]
```

Filter pools out of the black list
```ts
const pools = allPools.filter((addr) => !blacklistedPools.includes(addr) )
``` 
Show only in the UI pools that are not blacklisted

**Comment by luiseel** [comment]
@David-Sod sounds good. Can we add it to an env var?

**Comment by alejandrordzl** [comment]
@luis-stakeordie  Sure thing

**Comment by alejandrordzl** [comment]
@luis-stakeordie  the final approach would be something like this: 

Add inside .env a var called `BLACKLISTED_POOLS` with all black listed pools
```
BLACKLISTED_POOLS = [ "<pool_address>", "<pool_address>" ]
```
Parse this .env var to a json so it can reconized by js
```js
const blacklistedPools = JSON.parse(process.env.BLACKLISTED_POOLS);
```

Filter pools out of the black list
```ts
const pools = allPools.filter((addr) => !blacklistedPools.includes(addr) )
``` 
Show only in the UI pools that are not blacklisted

**Comment by luiseel** [comment]
@David-Sod awesome, go ahead.
